#' Calculates Harrell C-Index for the model
#'
#' @description
#' This function calculates the Harrell C Index value of the model in each of the imputed dataset stored in `data` as a long dataset. The Harrell's C Index calculation is realized using the `Hmisc::rcorr.cens` function [1]. After calculating the index in each imputed dataset then it aggregates them using the rubin rules with the `psfmi::pool_RR` function [2]. Finally, it stores the result inside the `c_index` attribute of `model`.
#'
#' @references
#' [1] F. E. Harrell, “Harrell Miscellaneous (R package Hmisc version 5.1-1),” R-project.org, Sep. 2023, doi: \link{https://cran.r-project.org/package=Hmisc}.
#'
#' [2] M. Heymans, “Prediction Model Pooling, Selection and Performance Evaluation Across Multiply Imputed Datasets (R package psfmi version 1.4.0),” R-project.org, Jun. 2023, doi: \link{https://cran.r-project.org/package=psfmi}.
#'
#' @param model generated by the function `mv_model`
#' @param data multiple imputation data organized as long dataset
#' @param .progress `TRUE` to render the progress bar `FALSE` otherwise
#'
#' @return the `model` with the Harrell C Index calculation stored in `$c_index`
#'
#' @importFrom Hmisc rcorr.cens
#' @importFrom dplyr %>% group_by group_map filter select
#' @importFrom tibble tibble as_tibble
#' @importFrom progress progress_bar
#'
#' @export
#'
#' @examples
#' calculate_c_index(model, data)
calculate_c_index <- function(model, data, .progress = TRUE) {
  stopifnot(is(model, "MiceExtVal"))
  stopifnot(is(data, "data.frame"))

  # Code for the progress bar
  if (.progress) {
    n_iter <- max(data$.imp)
    pb <- progress::progress_bar$new(
      format = "Calculating C-Index \t[:bar] :percent [Elapsed time: :elapsedfull || Remaining time: :eta]",
      total = n_iter,
      complete = "=",
      incomplete = "-",
      current = ">",
      clear = FALSE,
      width = 100
    )
  }

  # Calculates the C-Index value in each of the imputations.
  c_index_data <- data %>%
    dplyr::group_by(.imp) %>%
    dplyr::group_map(~ {
      # Progress bar code
      if (.progress) {
        pb$tick()
      }

      # Obtain the data of the event variable
      survival_data <- .x[[all.vars(model$formula)[1]]]
      Hmisc::rcorr.cens(
        # Get the predictions data for the imputation `.imp`.
        x = unlist(1 - (model$predictions_data %>% dplyr::filter(.imp == .y$.imp) %>% dplyr::select(prediction))),
        # Generates the outcome variable from `survival_data`
        S = survival::Surv(time = survival_data[, "time"], event = survival_data[, "status"])
      )
    }) %>%
    do.call(rbind, args = .)

  # Aggregates the results using rubin rules and populates the `c_index` parameter in the model
  model$c_index <- psfmi::pool_RR(
    est = c_index_data[, "C Index"],
    se = c_index_data[, "S.D."]/2,
    n = c_index_data[1, "n"],
    k = 1
  )

  return(model)
}
